config/routes.rb
StarterRubyRails::Application.routes.draw do

  

  root 'pages#home'

  get '/document/:id/:slug', to: 'application#document', constraints: {id: /[-_a-zA-Z0-9]{16}/}, as: :document

  get '/search', to: 'application#search', as: :search

  get '/home', to: 'pages#home', as: :home
  get '/about', to: 'pages#about', as: :about
  get '/blog', to: 'posts#index', as: :blog

  resources :products, only: [:index] do
    member do
      get '/:slug', to: 'products#show', as: :show
    end
  end

  resources :stores, only: [:index] do
    member do
      get '/:slug', to: 'stores#show', as: :show
    end
  end

  resources :jobs, only: [:index] do
    member do
      get '/:slug', to: 'jobs#show', as: :show
    end
  end

  resources :posts, only: [:index] do
    member do
      get '/:slug', to: 'posts#show', as: :show
    end
  end

  get '/signin', to: 'prismic_oauth#signin', as: :signin
  get '/callback', to: 'prismic_oauth#callback', as: :callback
  get '/signout', to: 'prismic_oauth#signout', as: :signout
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def index
    @document = PrismicService.get_document(api.bookmark("stores"), api, ref)
    @stores = api.form('stores').submit(ref)
  end

  def show
    @store = PrismicService.get_document(params[:id], api, ref)
    #TODO:view
  end
end

app/views/stores/index.html.erb
<div id="stores" class="main">

<section id="page-header">

  <div style="background-image: url(<%= @document['article.image'].get_view('main').url %>)">
    <div>
      <h1><%= @document['article.title'].as_text %></h1>

      <%= @document['article.short_lede'].as_text %>
    </div>
  </div>

</section>

<section id="page-body">
  <%= @document['article.content'].as_html_safe(link_resolver(maybe_ref)) %>

  <% @stores.each do |store| %>
      <article class="store" style="background-image: url(<%= store['store.image'].get_view('medium').url %>)">
        <%= link_to(show_store_path(store.id, slug: store.slug, ref: maybe_ref)) do %>
            <h3><%= store['store.name'].as_text %></h3>
        <% end %>
      </article>
  <% end %>

</section>
</div>

app/views/stores/show.html.erb
<%= @store.as_html_safe(link_resolver(maybe_ref)) %>