config/routes.rb
StarterRubyRails::Application.routes.draw do

  

  root 'pages#home'

  get '/document/:id/:slug', to: 'application#document', constraints: {id: /[-_a-zA-Z0-9]{16}/}, as: :document

  get '/search', to: 'application#search', as: :search

  get '/home', to: 'pages#home', as: :home
  get '/about', to: 'pages#about', as: :about
  get '/blog', to: 'posts#index', as: :blog

  resources :products, only: [:index] do
    member do
      get '/:slug', to: 'products#show', as: :show
    end
  end

  resources :stores, only: [:index] do
    member do
      get '/:slug', to: 'stores#show', as: :show
    end
  end

  resources :jobs, only: [:index] do
    member do
      get '/:slug', to: 'jobs#show', as: :show
    end
  end

  resources :posts, only: [:index] do
    member do
      get '/:slug', to: 'posts#show', as: :show
    end
  end

  get '/signin', to: 'prismic_oauth#signin', as: :signin
  get '/callback', to: 'prismic_oauth#callback', as: :callback
  get '/signout', to: 'prismic_oauth#signout', as: :signout
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_categories
  layout 'blog'


  def index
    category = params[:category]
    if category.blank?
      @posts = api.form('blog').submit(ref)
    else
      @posts = api.form('blog').query(category.blank?? '': "[[:d = at(my.blog-post.category, \"#{category}\")]]").submit(ref)
    end

  end

  def show
    @post = PrismicService.get_document(params[:id], api, ref)

    related_product_ids = @post['blog-post.relatedpost'].fragments.map(&:id)
    @related_posts = PrismicService.get_documents(related_product_ids, api, ref) #check if broken?

    related_product_ids = @post['blog-post.relatedproduct'].fragments.map(&:id) #check if broken?
    @related_products = PrismicService.get_documents(related_product_ids, api, ref)
  end

  def set_categories
    @categories ||= ["Announcements", "Do it yourself", "Behind the scenes"]
  end
end

app/views/posts/index.html.erb
<div class="main">
<section id="posts">

  <% @posts.results.take(10).each do |post| %>

      <article>
        <%=  %>

        <%= link_to show_post_path(post.id, slug: post.slug, ref: maybe_ref) do %>
          <em class="infos"><%= post["blog-post.date"].value %> by <%= post["blog-post.author"].as_text %></em>
          <h2><%= post["blog-post.body"].first_title %></h2>

          <p><%= post["blog-post.body"].first_paragraph_as_text %></p>

          <div style="background-image: url( <%= post["blog-post.body"].first_image.url %> ); background-size: cover"></div>

          <strong>Read more</strong>
        <% end %>
      </article>
  <% end %>

</section>
</div>

app/views/posts/show.html.erb
<div class="main">
  <section id="post">
    <em class="infos"><%= @post["blog-post.date"].value %> by <%= @post["blog-post.author"].as_text %></em>

    <article>
    <%= @post['blog-post.body'].as_html_safe(link_resolver(ref: maybe_ref)) %>
    </article>

    <% if @related_posts.length > 0 %>
        <h2><% if @related_posts.length == 1 %> This <% else %> These <% end %>should interest you too</h2>
        <ul>
            <% @related_posts.each do |post| %>
                <li>
                  <%= link_to show_post_path(post.id, slug: post.slug, ref: maybe_ref) do %>
                    <%= post['blog-post.body'].first_title %>
                  <% end %>
                </li>
            <% end %>
        </ul>
    <% end %>

    <% if @post['blog-post.allow_comments'] %>
        <h2>Comments</h2>

        <div id="fb-root"></div>
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

        <div class="fb-comments" data-href="<%= show_post_url(@post.id, slug: @post.slug, ref: maybe_ref) %>" data-width="640" data-num-posts="10"></div>
    <% end %>

    <aside>
        <% if @related_products.length > 0 %>
            <h2>Some pastries you should love</h2>

            <ul>
              <% @related_products.each do |p| %>
                  <li>
                    <%= link_to show_product_path(p.id, slug: p.slug, ref: maybe_ref) do %>
                    <img src="<%= p['product.image'].get_view('icon').url  %>">
                    <span><%= p['product.name'].as_text %></span>
                    <% end %>
                  </li>
              <% end %>
            </ul>
        <% end %>
    </aside>

  </section>
</div>