config/routes.rb
StarterRubyRails::Application.routes.draw do

  

  root 'pages#home'

  get '/document/:id/:slug', to: 'application#document', constraints: {id: /[-_a-zA-Z0-9]{16}/}, as: :document

  get '/search', to: 'application#search', as: :search

  get '/home', to: 'pages#home', as: :home
  get '/about', to: 'pages#about', as: :about
  get '/blog', to: 'posts#index', as: :blog

  resources :products, only: [:index] do
    member do
      get '/:slug', to: 'products#show', as: :show
    end
  end

  resources :stores, only: [:index] do
    member do
      get '/:slug', to: 'stores#show', as: :show
    end
  end

  resources :jobs, only: [:index] do
    member do
      get '/:slug', to: 'jobs#show', as: :show
    end
  end

  resources :posts, only: [:index] do
    member do
      get '/:slug', to: 'posts#show', as: :show
    end
  end

  get '/signin', to: 'prismic_oauth#signin', as: :signin
  get '/callback', to: 'prismic_oauth#callback', as: :callback
  get '/signout', to: 'prismic_oauth#signout', as: :signout
end

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Les bonnes choses</title>
  <%= yield :stylesheet %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <% if privileged_access? %>
    <div id="toolbar">
      <form method="GET">
        <label for="releaseSelector">See this website: </label>
        <select id="releaseSelector" name="ref" onchange="this.form.submit()">
          <% if !api.refs.map{|_,r| r.ref }.include?(ref) %>
            <option>?</option>
          <% end %>
          <option value="" <% if ref == api.master %>selected="selected"<% end %>>As currently seen by guest visitors</option>
          <optgroup label="Or preview the website in a future release:">
            <% api.refs.reject{|_,r| r.master? }.each do |_, r| %>
              <option value="<%= r.ref %>" <% if ref == r.ref %>selected="selected"<% end %>>
                As <%= r.label %> <%= r.scheduled_at.try(:strftime, "%Y-%m-%d") %>
              </option>
            <% end %>
          </optgroup>
        </select>
      </form>
    </div>
    <hr />
  <% end %>

  <%= yield :header %>
</header>

<%= yield %>

<footer>
  This is a demonstration website for <a href="http://prismic.io">prismic.io</a>

  <hr />
  <% if connected? %>
    <%= link_to signout_path do %>Sign out<% end %>
  <% else %>
    <%= link_to signin_path do %>Sign in to preview changes<% end %>
  <% end %>
</footer>

</body>
</html>

app/views/layouts/application.html.erb
<% content_for :stylesheet do %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<% end %>

<% content_for :header do %>
    <header>
      <nav>
        <h1><%= link_to('Les bonnes choses', home_path(ref: @maybe_ref)) %></h1>

        <ul>
          <li><%= link_to('About', about_path(ref: @maybe_ref)) %></li>
          <li><%= link_to('Stores', stores_path(ref: @maybe_ref)) %></li>
        </ul>
        <ul>
          <li><%= link_to('Jobs', jobs_path(ref: @maybe_ref)) %></li>
          <li><%= link_to('Our Blog', blog_path(ref: @maybe_ref)) %></li>
        </ul>

        <% link_to(about_path(ref: @maybe_ref)) do %>
            <span>Search</span>
        <% end %>

      </nav>
    </header>
<% end %>

<%= render 'layouts/base' %>

app/views/layouts/blog.html.erb
<% content_for :stylesheet do %>
    <%= stylesheet_link_tag    "blog", media: "all", "data-turbolinks-track" => true %>
<% end %>

<% content_for :header do %>
<header>

  <%= link_to root_path do %>
    <h1>Les Bonnes Choses</h1>
  <% end %>

  <nav>
    <ul>
      <li><%= link_to 'Home', home_path %></li>
      <% @categories.each do |category| %>
          <li><%= link_to category, posts_path(category: category) %></li>
      <% end %>
    </ul>
  </nav>

</header>

<% end %>

<%= render 'layouts/base' %>